Repository kommitters/mintacoin, pull requests merged in 2022-10, with the labels that each got.

#43 Implement the balance table for wallets
  lib/mintacoin/accounts/balance.ex
  lib/mintacoin/accounts/balances.ex
  lib/mintacoin/accounts/wallet.ex
  lib/mintacoin/assets/asset.ex
  priv/repo/migrations/20220930133102_create_balances.exs
  test/mintacoin/accounts/balances_test.exs
  test/support/balances/balance_factory.ex
  test/support/factory.ex
Labels: 👍 Feature

#50 Add authentication method with token
  config/dev.exs.example
  config/prod.exs
  config/test.exs
  lib/mintacoin_web/plugs/verify_api_token.ex
  lib/mintacoin_web/router.ex
  lib/mintacoin_web/views/error_view.ex
  test/mintacoin_web/controllers/accounts_controller_test.exs
Labels: 👍 Feature

#52 README documentation update
  .gitbook.yaml
  README.md
  docs/api_reference.md
Labels: 📖 Documentation

#68 Update readme documentation
  README.md
  config/dev.exs.example
Labels: 📖 Documentation

#75 Prepare release v0.2.2
  CHANGELOG.md
  mix.exs
Labels: 🚀 Next release

#71 Implement the create asset worker
  config/config.exs
  lib/mintacoin/accounts/balances.ex
  lib/mintacoin/accounts/encryption/cipher.ex
  lib/mintacoin/accounts/wallets.ex
  lib/mintacoin/assets/asset.ex
  lib/mintacoin/assets/asset_holders.ex
  lib/mintacoin/assets/assets.ex
  lib/mintacoin/assets/workers/create_asset.ex
  mix.exs
  priv/repo/migrations/20221011191742_update_asset_table.exs
  test/mintacoin/accounts/balances_test.exs
  test/mintacoin/accounts/wallets_test.exs
  test/mintacoin/assets/asset_holders_test.exs
  test/mintacoin/assets/assets_test.exs
  test/mintacoin/assets/workers/create_asset_test.exs
  test/support/assets/asset_factory.ex
  test/support/assets/crypto/stellar_mock.ex
Labels: 👍 Feature

#99 add credits section in README
  README.md
Labels: 📖 Documentation
