Repository kommitters/mintacoin, pull requests merged in 2022-07, with the labels that each got.

#99 98 Stellar implementation
  apps/mintacoin/lib/mintacoin/crypto.ex
  apps/mintacoin/lib/mintacoin/crypto/spec.ex
  apps/mintacoin/lib/mintacoin/crypto/stellar.ex
  apps/mintacoin/lib/mintacoin/crypto/stellar/accounts.ex
  apps/mintacoin/lib/mintacoin/crypto/stellar/assets.ex
  apps/mintacoin/lib/mintacoin/crypto/stellar/payments.ex
  apps/mintacoin/lib/mintacoin/crypto/tx_response.ex
  apps/mintacoin/mix.exs
  apps/mintacoin/test/mintacoin/crypto/stellar_test.exs
  config/dev.exs.example
  config/prod.exs
  config/test.exs
  mix.lock
Labels: 👍 Feature

#110 108 Blockchain tx schema and migration
  apps/mintacoin/lib/mintacoin/blockchain_txs/schema.ex
  apps/mintacoin/priv/repo/migrations/20220705201555_add_blockchain_txs_table.exs
Labels: 👍 Feature

#111 109 BlockchainTxs boundary and tests
  apps/mintacoin/lib/mintacoin/blockchain_txs/blockchain_txs.ex
  apps/mintacoin/test/mintacoin/blockchain_txs/blockchain_txs_test.exs
  apps/mintacoin/test/support/blockchain_txs/blockchain_txs_factory.ex
  apps/mintacoin/test/support/factory.ex
Labels: 👍 Feature

#118 116 Refactor wallets schema
  apps/mintacoin/lib/mintacoin/wallets/schema.ex
  apps/mintacoin/lib/mintacoin/wallets/wallets.ex
  apps/mintacoin/priv/repo/migrations/20220707160245_add_wallets_table.exs
  apps/mintacoin/test/mintacoin/wallets/wallets_test.exs
  apps/mintacoin/test/support/factory.ex
  apps/mintacoin/test/support/wallets/wallets_factory.ex
Labels: :recycle: Refactor

#121 120 AccountCreated event struct
  apps/mintacoin/lib/mintacoin/events/structs/account_created.ex
Labels: 👍 Feature

#122 113 Create `Core` layer with account creation pipeline
  apps/mintacoin/lib/mintacoin/core/accounts.ex
  apps/mintacoin/lib/mintacoin/crypto.ex
  apps/mintacoin/lib/mintacoin/crypto/spec.ex
  apps/mintacoin/lib/mintacoin/crypto/stellar.ex
  apps/mintacoin/lib/mintacoin/wallets/schema.ex
  apps/mintacoin/test/mintacoin/core/accounts_test.exs
  apps/mintacoin/test/mintacoin/crypto/crypto_test.exs
  apps/mintacoin/test/mintacoin/wallets/wallets_test.exs
Labels: 👍 Feature

#106 Implement Listener and Notifier to create an Account
  apps/mintacoin/lib/mintacoin/application.ex
  apps/mintacoin/lib/mintacoin/events/listener.ex
  apps/mintacoin/lib/mintacoin/repo.ex
  apps/mintacoin/priv/repo/migrations/20220708204956_create_blockchain_event_notifier.exs
  apps/mintacoin/test/mintacoin/events/listener_test.exs
  apps/mintacoin/test/support/blockchain_events/blockchain_events_factory.ex
Labels: 🔍 Review

#124 123 Implement create account consumer
  apps/mintacoin/lib/mintacoin/crypto/stellar/accounts.ex
  apps/mintacoin/lib/mintacoin/crypto/stellar/assets.ex
  apps/mintacoin/lib/mintacoin/crypto/stellar/payments.ex
  apps/mintacoin/lib/mintacoin/crypto/tx_response.ex
  apps/mintacoin/lib/mintacoin/events/consumer.ex
  apps/mintacoin/lib/mintacoin/events/listener.ex
  apps/mintacoin/lib/mintacoin/wallets/wallets.ex
  apps/mintacoin/test/mintacoin/events/consumer_test.exs
  apps/mintacoin/test/mintacoin/events/listener_test.exs
Labels: 👍 Feature

#129 Release v0.1.1
  CHANGELOG.md
  SECURITY.md
  mix.exs
Labels: 🚀 Next release
